name: flipperkit_dio_interceptor
description: flipperkit_dio_interceptor
version: 0.0.3
author: JianyingLi <lijy91@foxmail.com>
homepage: https://github.com/blankapp/flutter_flipperkit_plugins

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_flipperkit: ^0.0.27
  dio: ^4.0.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter