name: flipperkit_fish_redux_middleware
description: A new Flutter package project.
version: 0.0.1
author: JianyingLi <lijy91@foxmail.com>
homepage:

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  fish_redux: ^0.1.2
  uuid: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flipperkit: ^0.0.6
